name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: install yarn
      run: |
        cd apps/nowcasting-app
        yarn install
    - name: build & start app
      run: |
        cd apps/nowcasting-app
        yarn build
    - name: run tests
      run: |
        cd apps/nowcasting-app
        yarn start & sleep 5 && yarn test --coverage --coverageDirectory=../..
